name: Release

on:
  push:
    tags: "*"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: PUBLISH_USER
      GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
    services:
      rabbitmq:
        image: "rabbitmq:3.8"
        ports:
          - "5672:5672"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11.x
      - name: Lint
        run: ./gradlew spotlessCheck
      - name: Build
        run: ./gradlew -Pversion="$(basename $GITHUB_REF)" build
        env:
          RABBITMQ_HOST: localhost
          RABBITMQ_PORT: ${{ job.services.rabbitmq.ports[5672] }}
      - name: Publish
        run: ./gradlew -Pversion="$(basename $GITHUB_REF)" publish
