name: Release

on:
  push:
    tags: "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11.x
      - name: Build
        run: ./gradlew -Pversion="$(basename $GITHUB_REF)" build
        env:
          GITHUB_USER: PUBLISH_USER
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      - name: Publish
        run: ./gradlew -Pversion="$(basename $GITHUB_REF)" publish
        env:
          GITHUB_USER: PUBLISH_USER
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
