name: Test

on:
  push:
    branches:
      - develop
      - "feature/*"
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: PUBLISH_USER
      GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
    services:
      rabbitmq:
        image: "rabbitmq:3.8"
        ports:
          - "5672:5672"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11.x
      - name: Test
        run: ./gradlew test
        env:
          RABBITMQ_HOST: localhost
          RABBITMQ_PORT: ${{ job.services.rabbitmq.ports[5672] }}
      - name: Lint
        run: ./gradlew spotlessCheck
